apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-streaming-deployment
spec:
  selector:
    matchLabels:
      app: source-streaming-deployment1
  template:
    metadata:
      labels:
        app: source-streaming-deployment
    spec:
      containers:
      - name: source-streaming
        image: hctung57/source-streaming-ffmpeg:1.0
        ports:
        - containerPort: 1935
          name: container-port
          
---

apiVersion: v1
kind: Service
metadata:
  name: source-streaming-service
spec:
  selector:
    app: source-streaming-deployment
  ports:
  - name: output-streaming-port
    port: 1936
    targetPort: container-port



