apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-blur-deployment
spec:
  selector:
    matchLabels:
      app: background-blur-deployment
  template:
    metadata:
      labels:
        app: background-blur-deployment
    spec:
      containers:
      - name: background-blur
        image: hctung57/background-blur:1.0.2
        env:
          - name: SOURCE_STREAM_SERVICE
            value: "source-streaming-service"
          - name: SOURCE_RTMP_PORT
            value: "1936"
        ports:
        - containerPort: 1935
          name: container-port
---
apiVersion: v1
kind: Service
metadata:
  name: background-blur-service
spec:
  selector:
    app: background-blur-deployment
  ports:
  - name: output-streaming-port
    port: 5000
    targetPort: container-port
